### ISSUE TITLE
Magic Trees

### ISSUE THREAD

**Issue by jesus12123** [Broooklyn/runelite-external-plugins#27] opened 2021-03-10 04:43 UTC
Wonderful plugin. Thank you for your hard work. 

One suggestion:
I like to keep area sounds on while woodcutting both to hear chops as well as when the tree falls to make woodcutting more afkable.. Magic trees have their own noise that presents itself just when you stand next to them. I would like to see the option to mute the "magical" sound and just hear the axe hitting the tree and the sound of the tree falling.

Kind regards, 

Jesus

**Comment by Broooklyn** [comment] 2021-03-12 18:30
Duplicate of #3

**Closed as completed by Broooklyn** 2021-03-12 18:30 UTC
